version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80"
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"
    networks:
      - bbynet

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=label
      - POSTGRE_USER=$POSTGRES_USER
      - POSTGRE_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRE_HOST=18.222.251.216
      - POSTGRE_PORT=5432
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
    volumes:
      - ./mydata:/label-studio/data:rw
      - static:/label-studio/label_studio:rw
    command: [  "bash", "/label-studio/deploy/start_label_studio.sh" ]
    networks:
      - bbynet

volumes:
  static: {} 
  caddy_data:

networks:
  bbynet:
    name: bbynet
        