version: '3.3'

services:

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      XDG_DATA_HOME: /mount/server/data
      XDG_CONFIG_HOME: /mount/server/config
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/mount/server

  nginx:
    image: nginx:latest
    ports:
      - "80"
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"

  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    expose:
      - "8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=label
      - POSTGRE_USER="${POSTGRES_USER}"
      - POSTGRE_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRE_HOST=localhost:5432
      - POSTGRE_PORT=5432
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
    volumes:
      - ./mydata:/label-studio/data:rw
      - static:/label-studio/label_studio:rw
    command: [  "bash", "/label-studio/deploy/start_label_studio.sh" ]

volumes:
  static: {} 
  caddy_data:

